spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Keep this as none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false  # Add this to see SQL errors
      separator: ";"           # Add this for multi-statement files

  application:
    name: USER-SERVICE

server:
  port: 8081

# Add logging to debug schema execution
logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.boot.autoconfigure.sql.init: DEBUG
