auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: C:\loki\data
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  max_chunk_age: 87600h

compactor:
  retention_enabled: false

storage_config:
  filesystem:
    directory: C:\loki\chunks

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  allow_structured_metadata: false
  reject_old_samples: false
  reject_old_samples_max_age: 87600h
  retention_period: 0s
