services:
  hotel-postgres:
    image: postgres:latest
    container_name: hotel-postgres
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  hotel-service:
    build: .
    container_name: hotel-service
    ports:
      - "8082:8082"
    depends_on:
      - hotel-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hotel-postgres:5432/microservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: 2y2CWHTntzW2OK6jBrevJAa2Asa_21Q2AD8AHhhnesyUuqkNQ
    command: http hotel-service:8082
    depends_on:
      - hotel-service