services:
  ratingservice:
    build: .
    container_name: rating-service
    ports:
      - "8085:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/microservices
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-rating
    ports:
      - "4041:4040"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: start --all --config /etc/ngrok.yml
    depends_on:
      - ratingservice

volumes:
  mongodb_data: